remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins

theme: jekyll-theme-minimal
title: Davion's Portfolio
description: Portfolio of my Game Design learning progress.
